### PR TITLE
Finished Board Cards and Fixed Nav

### LINKED ISSUE #17: Board Card
Screenshot 2024-10-04 at 8 57 58 AM

### PR DESCRIPTION
**Pull request by DannielK**
image
Made temp data in data/Board.ts

image
Fixed Nav links being not selectable and underline bar not showing

Note: Didn't responsify board.tsx bc unsure what kind of spacing and how many cards per row is wanted for smaller viewports

### CODE REVIEW

File: src/components/Board.tsx [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import Card from "./Card";
+import { ITEMS } from "@/data/board";
+
+const Board = () => {
+  return (
+    <div className="grid grid-cols-3 gap-x-32 gap-y-44">
```
Comment (stormyy00) [inline src/components/Board.tsx]: try use flex-wrap and like gap-10 no need to have big gap #'s\

should fix responsiveness for now

**Review by stormyy00 — APPROVED** [review]
